# Generated by Django 4.2.5 on 2023-09-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dooapp', '0002_formitens_remove_template_codigo_and_more'),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='templates',
            field=models.ManyToManyField(related_name='templates', to='dooapp.template'),
        ),
    ]
