# Generated by Django 4.2.5 on 2023-09-30 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('collection', models.CharField(blank=True, max_length=200, verbose_name='collection')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='TypeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('value', models.TextField(blank=True, null=True, verbose_name='value')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbookParameters', to='iac.typeinput')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('value', models.TextField(blank=True, null=True, verbose_name='value')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryParameters', to='iac.typeinput')),
            ],
        ),
        migrations.CreateModel(
            name='AnsibleModuleVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('variable_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='type')),
                ('choices', models.CharField(blank=True, max_length=255, null=True, verbose_name='choices')),
                ('required', models.BooleanField(default=False)),
                ('module', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ansible_modules', to='iac.ansiblemodule')),
            ],
        ),
    ]
