# Generated by Django 4.2.5 on 2023-09-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dooapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.IntegerField(choices=[(1, 'Text')], default=1)),
                ('label', models.CharField(max_length=100, verbose_name='label')),
            ],
        ),
        migrations.RemoveField(
            model_name='template',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='template',
            name='titulo',
        ),
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='yaml',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='form_itens',
            field=models.ManyToManyField(related_name='form_itens', to='dooapp.formitens'),
        ),
    ]
