# Generated by Django 4.2.5 on 2023-09-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dooapp', '0002_formitens_remove_template_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='form_itens',
            field=models.ManyToManyField(null=True, related_name='form_itens', to='dooapp.formitens'),
        ),
        migrations.RemoveField(
            model_name='template',
            name='service',
        ),
        migrations.AlterField(
            model_name='template',
            name='yaml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='service',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, to='dooapp.service'),
            preserve_default=False,
        ),
    ]
