# Generated by Django 4.2.5 on 2023-09-18 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dooapp', '0003_alter_template_form_itens_remove_template_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dooapp.service'),
        ),
    ]
